### ISSUE TITLE
DB (PostgreSQL) User Credential

### ISSUE THREAD

**Issue by crazydevlegend** [leosuncin/nest-auth-example#1243]
I just cloned this repo and I'm having some errors while running `yarn run typeorm migration:run`
![image](https://user-images.githubusercontent.com/94694049/232595698-d2234686-5df0-4e2b-b3b9-14c13b474e56.png)

And here's my `.env` file (am wondering if these values are right for the dockerized image)
![image](https://user-images.githubusercontent.com/94694049/232596021-d508f772-4a51-44c9-ad77-8a5252d45fa3.png)

**Comment by crazydevlegend** [comment]
![image](https://user-images.githubusercontent.com/94694049/232614062-89e170fd-a95a-4d5a-8ec5-ca76de026487.png)

**Comment by leosuncin** [comment]
Replace the values in your connection connection string with the ones you're using

By example:

```
DATABASE_URL=postgres://user:password@postgres-host-name:5432/nestjs
```

Sorry, I'm writing from my phone, I can check it later if you need more help.

**Comment by crazydevlegend** [comment]
I run your docker container, so I guess, it's built-in setting?

**Comment by crazydevlegend** [comment]
![image](https://user-images.githubusercontent.com/94694049/232620948-434c79ca-6357-4303-9660-0bfbad63d20c.png)
![image](https://user-images.githubusercontent.com/94694049/232620975-3f05e13a-52bf-44f4-bf36-8009ed409bf9.png)
![image](https://user-images.githubusercontent.com/94694049/232620990-1422ed1c-43ff-47c5-84a1-5b04cfd041cc.png)

**Comment by leosuncin** [comment]
The values in the `.env.example` are examples values and they should be replaced with a more accurate ones.

The default ones should work when you run the following steps:

- Copy the default values: `cp .env.example .env`
- Run the services with docker compose: `docker compose up -d`
- Run the project with a local node.js installation: `npm run start:dev`

This is because Docker Compose will run an instance of PostgreSQL listening on _localhost:5432_ with the user `user` and password `password`

When the project run as a Docker container the PostgreSQL instance is not accessible through _localhost:5432_, you'll need to link both containers (the project and PostgreSQL) or run in the same network. Google it for more information

**Comment by leosuncin** [comment]
The values in the `.env.example` are examples values and they should be replaced with a more accurate ones.

The default ones should work when you run the following steps:

- Copy the default values: `cp .env.example .env`
- Run the services with docker compose: `docker compose up -d`
- Run the project with a local node.js installation: `npm run start:dev`

This is because Docker Compose will run an instance of PostgreSQL listening on _localhost:5432_ with the user `user` and password `password`

When the project run as a Docker container the PostgreSQL instance is not accessible through _localhost:5432_, you'll need to link both containers (the project and PostgreSQL) or run in the same network. Google it for more information

**Comment by crazydevlegend** [comment]
Yeah, that's exactly what I did (just followed steps in README)

**Comment by crazydevlegend** [comment]
But when I run `yarn start:dev`, it shows the following error:
![image](https://user-images.githubusercontent.com/94694049/232626310-89cd98d4-37ed-4aaf-a1d3-90977882195d.png)

**Comment by leosuncin** [comment]
Hi @crazydevlegend, I updated the dependencies of the project, pull the changes and try again, please

**Comment by crazydevlegend** [comment]
@leosuncin I'm using windows 11, and am not sure if this template work on Windows either.
when i run `npm run typeorm migration:run`, it said, `NODE_OPTIONS` undefined.
So I installed `wi-node-env`, and it shows another error.
![image](https://user-images.githubusercontent.com/94694049/232850205-eaad5f4e-d480-4c8f-85a5-17f581218223.png)

**Comment by crazydevlegend** [comment]
oh, i just fixed this issue by installing `ts-node`, .thanks 🙏

**Comment by leosuncin** [comment]
> @leosuncin I'm using windows 11, and am not sure if this template work on Windows either. when i run `npm run typeorm migration:run`, it said, `NODE_OPTIONS` undefined. So I installed `wi-node-env`, and it shows another error. ![image](https://user-images.githubusercontent.com/94694049/232850205-eaad5f4e-d480-4c8f-85a5-17f581218223.png)

Sorry, I'm not giving support for Windows since I don't use it anymore, but it should work with Bash for Windows or Windows Subsystem for Linux (WSL), due to this template heavily rely on environment variables as Bash define it. I haven't used `wi-node-env` but I know that `cross-env` works.

**Comment by salahawk** [comment]
@leosuncin I wonder how I can migrate the database once I add more entities.

**Comment by crazydevlegend** [comment]
You should take a look at your docker configuration, @salahawk

**Comment by leosuncin** [comment]
> @leosuncin I wonder how I can migrate the database once I add more entities. and also when I changed the database name?

# How to add more entities

1. Create a new entity somewhere in your project

```typescript
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Pet {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;
}
```

2. Register it the `data-source.ts` file

```typescript
import { Pet } from './wherever/pet.entity';

export const dataSourceOptions: DataSourceOptions = {
  // ...
  entities: [ /* the other entities*/, Pet],
  // ...
};
```

3. Generate the new migration using TypeORM CLI

```bash
npm run typeorm migration:generate src/migrations/NameOfTheMigration
```

4. Review the generated migration and modified it as needed

5. Then add it to `data-source.ts` file

```typescript
import { Pet } from './wherever/pet.entity';
import { NameOfTheMigration } from './migrations/name-of-the-migration';

export const dataSourceOptions: DataSourceOptions = {
  // ...
  entities: [ /* the other entities*/, Pet],
  migrations: [
    /* the other migrations, keep in mind that the order is important! */
    NameOfTheMigration,
  ],
  // ...
};
```

6. Run the migrations

```bash
npm run typeorm migration:run
```

Check the documentation for further information https://orkhan.gitbook.io/typeorm/docs/migrations

# Change the name of the database

The name of the database doesn't need to be "nestjs", it can be whatever you pick for, and set it in '.env'.

If you want to change the name of an existing database [google it](https://letmegooglethat.com/?q=PostgreSQL+change+database+name) and again change it in the `.env` file

**Comment by salahawk** [comment]
@leosuncin What if I want to remove an entity? (aka. `TODO` entity)
I'm building my own app, and want to remove this `TODO` entity, but when I run `npm run typeorm migration:generate src/migrations/RemovedTODO` after removing `TODO` in the `entities` list in `data-source.ts`, it says, no changes were found!!! (but actually, there's been changes - `TODO` entity has been removed)

![image](https://github.com/leosuncin/nest-auth-example/assets/99642582/78951245-6218-4aba-aaa6-4083329091f5)

Do you have any ideas on this?

Thanks in advance

**Comment by leosuncin** [comment]
> @leosuncin What if I want to remove an entity? (aka. `TODO` entity)
> I'm building my own app, and want to remove this `TODO` entity, but when I run `npm run typeorm migration:generate src/migrations/RemovedTODO` after removing `TODO` in the `entities` list in `data-source.ts`, it says, no changes were found!!! (but actually, there's been changes - `TODO` entity has been removed)
> 
> ![image](https://github.com/leosuncin/nest-auth-example/assets/99642582/78951245-6218-4aba-aaa6-4083329091f5)
> 
> Do you have any ideas on this?
> 
> Thanks in advance

This is not related to this project, so I won't go deep but removing a entity from the data source doesn't necessary means that the table must be removed just ignored by the ORM, if you still need to remove the table create an empty migration and add the drop table statement

**Comment by salahawk** [comment]
> > @leosuncin What if I want to remove an entity? (aka. `TODO` entity)
> > I'm building my own app, and want to remove this `TODO` entity, but when I run `npm run typeorm migration:generate src/migrations/RemovedTODO` after removing `TODO` in the `entities` list in `data-source.ts`, it says, no changes were found!!! (but actually, there's been changes - `TODO` entity has been removed)
> > ![image](https://user-images.githubusercontent.com/99642582/241243668-78951245-6218-4aba-aaa6-4083329091f5.png)
> > Do you have any ideas on this?
> > Thanks in advance
> 
> This is not related to this project, so I won't go deep but removing a entity from the data source doesn't necessary means that the table must be removed just ignored by the ORM, if you still need to remove the table create an empty migration and add the drop table statement

So you mean, typeorm does not automatically generate that DROP statement, right?

**Comment by leosuncin** [comment]
This is not proper place to ask questions about any other library if you have any technical questions ask them on stackoverflow, I will only respond to questions related to the functionality of this repository
