### ISSUE TITLE
Question on Demo API : TODO

### ISSUE THREAD

**Issue by crazydevlegend** [leosuncin/nest-auth-example#1244]
@leosuncin Thanks for you updates.
I just pulled the latest commits and it works pretty fine.
I'm not sure if I made a mistake or not, but when I make a GET request `/todo:id`, it returns the list of TO-DOs, not only the one with that ID.
![image](https://user-images.githubusercontent.com/94694049/232912558-45dfa2af-b3dc-4d1a-b464-717c779ee55d.png)

Can you please take a look into this?

**Comment by leosuncin** [comment]
To get one todo by id use `GET /todo/:id`, replace `:id` with the specific id, by example `GET /todo/1`
